version: '2.0'
services:

  ## GLOBAL ##

  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./nginx/data/certs:/etc/nginx/certs:ro"


  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx/data/tmpl/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf


  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./nginx/data/certs:/etc/nginx/certs:rw"
    environment:
      - "NGINX_DOCKER_GEN_CONTAINER=nginx-gen"


  editor:
    image: node:boron
    volumes:
      - ./public:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - "HOSTNAME=h3edit.com"
      - "PORT=4000"
      - "VIRTUAL_PORT=4000"
      - "VIRTUAL_HOST=h3edit.com"
      - "VIRTUAL_NETWORK=nginx-proxy"
      - "LETSENCRYPT_HOST=h3edit.com"
      - "LETSENCRYPT_EMAIL=webmaster@h3edit.com"
    command: sh -c 'npm install -g http-serve && http-serve -p 4000'
    ports:
      - "0.0.0.0:4000:4000"
